- name: Work in Progress
  color: '2a0944'
  description: Not yet ready for review

- name: Ready for Review
  color: '33FFE4'
  description: Ready to be reviewed

- name: Experiment
  color: 'FF7B33'
  description: This may or may not be a good idea, just trying things out

- name: Help Wanted
  color: '334BFF'
  description: Not yet ready for review but could do with some help

- name: Bug
  color: 'FF336F'
  description: Something isn't right here

- name: Untriaged
  color: 'FBF000'
  description: This bug has not yet been reviewed

- name: Won't Do
  color: '797979'
  description: We have reviewed this piece of work and decided not to do it (see comments)

- name: p1
  color: '7AFFE0'
  description: Priority 1 work - highest

- name: p2
  color: '7AFFE0'
  description: Priority 2 work

- name: p3
  color: '7AFFE0'
  description: Priority 3 work - lowest

- name: Documentation
  color: '7ABBFF'
  description: Request contains update to documentation

- name: Program Changes
  color: 'EBFF7A'
  description: Changes to a program

- name: Github Config
  color: '325ea8'
  description: Changes to github configurations - for example workflow files

- name: CICD Tools
  color: '325ea8'
  description: Changes to tools enabling CI/CD

- name: Security
  color: 'ffbb00'
  description: Security issue

- name: Tests
  color: 'a2e0b2'
  description: Updates to tests
