[programs.localnet]
protocol_event = "mpeq1VkcGKDWS7ELiQJ2diRPX9vHQb27FruqcoxhPqF"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn runJestTests"
