name: CD - Deploy Program (Manual)

on:
  workflow_dispatch:
    inputs:
      deploy_type:
        type: choice
        description: Deploy type
        required: true
        options:
        - dev
        - stable
      build:
        type: string
        required: true
        description: "Build to deploy e.g. 0.1.0.dev.4c721b7b"
      environment:
        type: choice
        description: Environment to deploy to
        options:
        - devnet
        - testnet
      note:
        type: string
        description: "Note (optional)"
        required: false
        default: "Manual Deploy"

jobs:
  ci_build:
    uses: BetDexLabs/external-events/.github/workflows/cd_deploy_.yml@main
    with:
      deploy_type: ${{ github.event.inputs.deploy_type }}
      build: ${{ github.event.inputs.build }}
      environment: ${{ github.event.inputs.environment }}
      note: ${{ github.event.inputs.note }}
    secrets:
      access_key_id: ${{ secrets.ORG_AWS_ACCESS_KEY_ID }}
      access_key: ${{ secrets.ORG_AWS_SECRET_KEY }}
      region: ${{ secrets.AWS_REGION }}
      wallet_pass: ${{ secrets.WALLET_PASSPHRASE }}
      gh_token: ${{ secrets.GITHUB_TOKEN }}
