name: CICD - Dev Build & Release

on:
  push:
    paths:
      - 'programs/externalevent/**'
    branches: [ main ]

jobs:
  ci_build:
    uses: BetDexLabs/external-events/.github/workflows/ci_build_.yml@chore/bump-dependencies
    with:
      build_type: dev
      solana_version: ${{ vars.ORG_SOLANA_VERSION }}
    secrets:
      access_key_id: ${{ secrets.ORG_AWS_ACCESS_KEY_ID }}
      access_key: ${{ secrets.ORG_AWS_SECRET_KEY }}
      region: ${{ secrets.AWS_REGION }}

  cd_deploy:
    needs: ci_build
    uses: BetDexLabs/external-events/.github/workflows/cd_deploy_.yml@chore/bump-dependencies
    with:
      deploy_type: dev
      build: ${{ needs.ci_build.outputs.build_version }}
      environment: devnet
      note: "Auto-Deploy to Devnet"
      solana_version: ${{ vars.ORG_SOLANA_VERSION_DEPLOY }}
    secrets:
      access_key_id: ${{ secrets.ORG_AWS_ACCESS_KEY_ID }}
      access_key: ${{ secrets.ORG_AWS_SECRET_KEY }}
      region: ${{ secrets.AWS_REGION }}
      wallet_pass: ${{ secrets.ORG_DEV_WALLET_PASSPHRASE }}
      gh_token: ${{ secrets.GITHUB_TOKEN }}
