name: CI - Build External Events

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    paths:
      - 'programs/externalevent/**'
      - 'tests/**'
    branches: [ main ]

jobs:
  ci_build:
    uses: BetDexLabs/external-events/.github/workflows/ci_build_.yml@main
    if: github.event.pull_request.draft == false
    with:
      build_type: dev
    secrets:
      access_key_id: ${{ secrets.ORG_AWS_ACCESS_KEY_ID }}
      access_key: ${{ secrets.ORG_AWS_SECRET_KEY }}
      region: ${{ secrets.AWS_REGION }}
